name: SimpleTM
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - einops=0.8.1
  - matplotlib=3.7.0
  - numpy=1.23.5
  - scikit-learn=1.2.2
  - scipy=1.13.1
  - sympy=1.13.3
  - pandas=1.5.3
  - pip:
    - reformer-pytorch==1.4.4
    - PyWavelets
